feat: writer for mz_parquet v0.2 format
compomics/ThermoRawFileParser pull request #188
Opened 2024-11-15 21:47 UTC by lazear

This PR implements a new writer for the parquet output format, in line with the specification used here: https://github.com/lazear/mz_parquet

This is a "long" format for mass spectrometry data, where each row in the output file represents an ion with an associated m/z & intensity in the raw data. This enables highly efficient downstream applications for XIC generation, searching data, etc, since filters can be constructed for one 'column' (e.g. `mz`, or `precursor_mz`) at a time and leverage SIMD.

The other benefit of the long format is that it is flexible - additional columns can be added by writers, and simply ignored (never read from disk) by downstream software if they don't need that column.

Note that this implementation (raw -> mz_parquet) produces mzparquet files with slightly different results than raw -> mzML -> mz_parquet converter, likely because of differences in how centroid streams are created. Please feel free to suggest the best way to pull out the raw data, and I'm happy to change it.

2024-11-16 08:02 UTC, timosachsenberg commented
@ypriverol would be interesting to benchmark XIC extraction (e.g. randomly placed m/z + rt ranges).

2024-11-16 17:17 UTC, lazear commented
> @ypriverol would be interesting to benchmark XIC extraction (e.g. randomly placed m/z + rt ranges).

```py
# github.com/lazear/mz_parquet commit: ef5c124f4890c0f025544f8fe7c6e09a33a813e8
# long format: cargo run --release LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_01.mzML --long
# wide format: cargo run --release LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_01.mzML
import polars as pl
import time

mz = 284.0106
tol = mz * 20E-6
rt = 12.7

t0 = time.time()
df = pl.scan_parquet("LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_01.mzparquet.long").filter(
    pl.col("rt").is_between(rt - 1, rt + 1)
    & pl.col("mz").is_between(mz - tol, mz + tol)
).collect()
t1 = time.time()

print(f"long: {t1 - t0:0.4}s")

t0 = time.time()
df = pl.scan_parquet("LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_01.mzparquet.wide").filter(
    pl.col("scan_start_time").is_between(rt - 1, rt + 1)
    & pl.col("mz")
        .list.eval(pl.element().is_between(mz - tol, mz + tol))
        .list.any()
).collect()
t1 = time.time()

print(f"wide: {t1 - t0:0.4}s")

```
```
> long: 0.006542s
> wide: 0.644s
```

2024-11-18 09:12 UTC, timosachsenberg commented
Stupid beginner question, but would you also need a collect() in the later benchmark?

2025-01-03 10:17 UTC, ypriverol approved these changes

2025-01-03 10:46 UTC, caetera requested changes

2025-01-03 10:46 UTC, caetera commented on Writer/ParquetSpectrumWriter.cs
> +                else
The third (else) branch seems to do the same as the second one (else if). Is this intended?

2025-01-03 10:46 UTC, caetera commented on Writer/ParquetSpectrumWriter.cs
> +                // Pull out m/z and intensity values
Do we always want to have centroids written to the file? Should we use the same approach as other file formats? By default only centroids, and profile data if `-p` is provided

2025-01-03 10:46 UTC, caetera commented on Writer/ParquetSpectrumWriter.cs
> +            var last_scans = new Dictionary<int, uint>();
Do we want to detect precursor scan the same way as for the other formats or keep this (much simpler) way?

2025-01-03 10:46 UTC, caetera commented on Writer/ParquetSpectrumWriter.cs
> +                    var rx = scanFilter.GetReaction(0);
This will only read the first reaction, i.e. for anything other than MS2 without the supplemental activation it won't be accurate. Is this intended?

2025-01-03 10:46 UTC, caetera commented on Writer/ParquetSpectrumWriter.cs
> +                    isolation_lower = (float)(rx.PrecursorMass - rx.IsolationWidth / 2);
Do we want to keep the result consistent with other formats?

2025-01-03 10:46 UTC, caetera commented on Writer/ParquetSpectrumWriter.cs
> +                var trailer = raw.GetTrailerExtraInformation(scanNumber);
It is probably better to use Trailer object, similarly to mzML implementation

2025-03-04 19:00 UTC, caetera commented
@lazear Based on your PR, I have implemented a writer for mzParquet with a minor schema change, producing output similar to other supported formats. Since I could not commit directly to this PR branch, I created a new PR #192.

2025-03-04 19:02 UTC, merged